[package]
name = "adventofcode_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
itertools = "0.10.5"
lazy_static = "1.4.0"
ndarray = "0.15.6"
nom = "7.1.1"
termion = "2.0.1"
